use reverse_assistant_lib::models::ghidra_export::GhidraExport;
use reverse_assistant_lib::services::comparison::{compare_projects, MatchMethod, UnmatchedReason};

const REAL_ELF_EXPORT_JSON: &str = include_str!("fixtures/real-fauxware-export-v2.json");

#[test]
fn identical_real_elf_projects_match_every_function_without_guessing() {
    let export = GhidraExport::parse_and_validate(REAL_ELF_EXPORT_JSON)
        .expect("the real ELF fixture should parse");

    let comparison = compare_projects(&export, &export);

    assert!(comparison.same_binary);
    assert_eq!(comparison.matches.len(), export.functions.len());
    assert!(comparison.unmatched_a.is_empty());
    assert!(comparison.unmatched_b.is_empty());

    let authenticate = comparison
        .matches
        .iter()
        .find(|function_match| function_match.function_a.name == "authenticate")
        .expect("the real authenticate function should be paired");
    assert_eq!(authenticate.method, MatchMethod::SymbolName);
    assert!(authenticate.changes.is_empty());

    assert!(comparison.matches.iter().any(|function_match| {
        function_match.function_a.name.starts_with("FUN_")
            && function_match.method == MatchMethod::SameAddress
    }));
}

#[test]
fn a_real_stripped_elf_with_a_different_hash_keeps_auto_names_unmatched() {
    let export_a = GhidraExport::parse_and_validate(REAL_ELF_EXPORT_JSON)
        .expect("the real ELF fixture should parse");
    let mut export_b = export_a.clone();
    export_b.program.sha256 = "f".repeat(64);

    let comparison = compare_projects(&export_a, &export_b);

    assert!(!comparison.same_binary);
    assert!(comparison.matches.iter().any(|function_match| {
        function_match.function_a.name == "authenticate"
            && function_match.method == MatchMethod::SymbolName
    }));
    assert!(comparison.unmatched_a.iter().any(|function| {
        function.name.starts_with("FUN_") && function.reason == UnmatchedReason::AutoGeneratedName
    }));
}
