use std::collections::HashMap;

use crate::models::ghidra_export::{GhidraExport, GhidraFunction};

// How a matched pair of functions was identified, so the UI can explain the
// pairing rather than presenting it as unqualified fact.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MatchMethod {
    // Same (namespace, name) key, and that key is unique on both sides.
    SymbolName,
    // Same entry_address. Only ever produced when both exports report the
    // same `program.sha256` -- addresses are not comparable across
    // different binaries, so this pass never runs otherwise.
    SameAddress,
}

// Why a function could not be matched by name. Kept distinct from "added" or
// "removed": a name-based matcher genuinely cannot tell whether an unmatched
// function is new, gone, or just renamed/stripped -- claiming otherwise
// would fabricate certainty the data doesn't support.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum UnmatchedReason {
    // Ghidra's own placeholder naming (e.g. `FUN_00400500`) carries no
    // real identity information, so it is never used to match.
    AutoGeneratedName,
    // The (namespace, name) key isn't unique within this analysis (e.g.
    // the same import name repeated across PLT/GOT thunk levels), so
    // matching on it would be a coin flip.
    AmbiguousName,
    // The name was significant and unique here, but no function with the
    // same (namespace, name) key exists on the other side.
    NoCandidate,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize)]
pub struct FunctionRef {
    pub entry_address: String,
    pub name: String,
    pub namespace: Option<String>,
}

impl FunctionRef {
    fn from_function(function: &GhidraFunction) -> Self {
        FunctionRef {
            entry_address: function.entry_address.clone(),
            name: function.name.clone(),
            namespace: function.namespace.clone(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum FunctionChangeKind {
    ReturnType,
    Parameters,
    ThunkStatus,
    ExternalStatus,
    OutgoingCallCount,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize)]
pub struct FunctionChange {
    pub kind: FunctionChangeKind,
    pub before: String,
    pub after: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize)]
pub struct FunctionMatch {
    pub method: MatchMethod,
    // True when both functions also share the same entry_address --
    // informational even for a `SymbolName` match (extra corroboration the
    // UI can surface), always true for a `SameAddress` match by construction.
    pub same_address: bool,
    pub function_a: FunctionRef,
    pub function_b: FunctionRef,
    // Empty means no detected difference between the two sides.
    pub changes: Vec<FunctionChange>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize)]
pub struct UnmatchedFunction {
    pub entry_address: String,
    pub name: String,
    pub namespace: Option<String>,
    pub reason: UnmatchedReason,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize)]
pub struct ProjectComparison {
    // Whether both exports report the same `program.sha256` -- the only
    // signal this comparison uses to decide whether address-based matching
    // is meaningful. There is no broader notion of "related binary" beyond
    // this exact check.
    pub same_binary: bool,
    pub matches: Vec<FunctionMatch>,
    pub unmatched_a: Vec<UnmatchedFunction>,
    pub unmatched_b: Vec<UnmatchedFunction>,
}

// Ghidra's placeholder name for a function it could not otherwise name,
// e.g. `FUN_00400500` or (for an unresolved thunk) `thunk_FUN_00400500`.
// Carries no real identity information, so it must never be used to match
// two functions across analyses.
fn is_auto_generated_name(name: &str) -> bool {
    let core = name.strip_prefix("thunk_").unwrap_or(name);

    match core.strip_prefix("FUN_") {
        Some(rest) => !rest.is_empty() && rest.chars().all(|c| c.is_ascii_hexdigit()),
        None => false,
    }
}

type MatchKey = (Option<String>, String);

fn match_key(function: &GhidraFunction) -> MatchKey {
    (function.namespace.clone(), function.name.clone())
}

// Groups every function with a significant (non-auto-generated) name by its
// (namespace, name) key. A key mapping to more than one function is
// inherently ambiguous and must never be used to match.
fn index_by_match_key(export: &GhidraExport) -> HashMap<MatchKey, Vec<&GhidraFunction>> {
    let mut index: HashMap<MatchKey, Vec<&GhidraFunction>> = HashMap::new();

    for function in &export.functions {
        if is_auto_generated_name(&function.name) {
            continue;
        }

        index.entry(match_key(function)).or_default().push(function);
    }

    index
}

fn unmatched_reason(
    index: &HashMap<MatchKey, Vec<&GhidraFunction>>,
    function: &GhidraFunction,
) -> UnmatchedReason {
    if is_auto_generated_name(&function.name) {
        return UnmatchedReason::AutoGeneratedName;
    }

    match index.get(&match_key(function)) {
        Some(candidates) if candidates.len() > 1 => UnmatchedReason::AmbiguousName,
        _ => UnmatchedReason::NoCandidate,
    }
}

fn signature(function: &GhidraFunction) -> String {
    function
        .parameters
        .iter()
        .map(|parameter| parameter.data_type.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

fn diff_function(a: &GhidraFunction, b: &GhidraFunction) -> Vec<FunctionChange> {
    let mut changes = Vec::new();

    if a.return_type != b.return_type {
        changes.push(FunctionChange {
            kind: FunctionChangeKind::ReturnType,
            before: a.return_type.clone(),
            after: b.return_type.clone(),
        });
    }

    let signature_a = signature(a);
    let signature_b = signature(b);
    if signature_a != signature_b {
        changes.push(FunctionChange {
            kind: FunctionChangeKind::Parameters,
            before: signature_a,
            after: signature_b,
        });
    }

    if a.is_thunk != b.is_thunk {
        changes.push(FunctionChange {
            kind: FunctionChangeKind::ThunkStatus,
            before: a.is_thunk.to_string(),
            after: b.is_thunk.to_string(),
        });
    }

    if a.is_external != b.is_external {
        changes.push(FunctionChange {
            kind: FunctionChangeKind::ExternalStatus,
            before: a.is_external.to_string(),
            after: b.is_external.to_string(),
        });
    }

    if a.calls.len() != b.calls.len() {
        changes.push(FunctionChange {
            kind: FunctionChangeKind::OutgoingCallCount,
            before: a.calls.len().to_string(),
            after: b.calls.len().to_string(),
        });
    }

    changes
}

fn make_match(method: MatchMethod, a: &GhidraFunction, b: &GhidraFunction) -> FunctionMatch {
    FunctionMatch {
        method,
        same_address: a.entry_address == b.entry_address,
        function_a: FunctionRef::from_function(a),
        function_b: FunctionRef::from_function(b),
        changes: diff_function(a, b),
    }
}

// Matches functions between two analyses. Two passes today:
//
//   1. By (namespace, name), when that key is significant (not an
//      auto-generated placeholder) and unique on both sides.
//   2. By identical entry_address, only when both exports report the same
//      `program.sha256` -- and only among functions the first pass left
//      unmatched.
//
// Whatever remains after both passes is reported as `unmatched_a`/
// `unmatched_b`, each carrying the reason matching didn't happen -- never
// asserted as "added" or "removed", since a name-based matcher cannot
// distinguish those from a rename or from stripping.
//
// A future BSim-based similarity pass over stripped/anonymous functions
// would slot in as a third pass here, consuming exactly the functions that
// remain in `remaining_a`/`remaining_b` below before they're turned into
// the final unmatched lists.
pub fn compare_projects(a: &GhidraExport, b: &GhidraExport) -> ProjectComparison {
    let same_binary = a.program.sha256 == b.program.sha256;

    let index_a = index_by_match_key(a);
    let index_b = index_by_match_key(b);

    let mut matches = Vec::new();

    let mut remaining_a: HashMap<&str, &GhidraFunction> = a
        .functions
        .iter()
        .map(|function| (function.entry_address.as_str(), function))
        .collect();
    let mut remaining_b: HashMap<&str, &GhidraFunction> = b
        .functions
        .iter()
        .map(|function| (function.entry_address.as_str(), function))
        .collect();

    // Pass 1: significant, unique (namespace, name) match.
    for (key, candidates_a) in &index_a {
        if candidates_a.len() != 1 {
            continue;
        }

        let Some(candidates_b) = index_b.get(key) else {
            continue;
        };

        if candidates_b.len() != 1 {
            continue;
        }

        let function_a = candidates_a[0];
        let function_b = candidates_b[0];

        remaining_a.remove(function_a.entry_address.as_str());
        remaining_b.remove(function_b.entry_address.as_str());

        matches.push(make_match(MatchMethod::SymbolName, function_a, function_b));
    }

    // Classify why every function still remaining wasn't matched by name,
    // before pass 2 potentially removes some of them by address instead --
    // whatever pass 2 doesn't claim keeps this classification in the final
    // unmatched output.
    let mut reasons_a: HashMap<&str, UnmatchedReason> = remaining_a
        .values()
        .map(|function| {
            (
                function.entry_address.as_str(),
                unmatched_reason(&index_a, function),
            )
        })
        .collect();
    let mut reasons_b: HashMap<&str, UnmatchedReason> = remaining_b
        .values()
        .map(|function| {
            (
                function.entry_address.as_str(),
                unmatched_reason(&index_b, function),
            )
        })
        .collect();

    // Pass 2: identical address, only meaningful when both sides are
    // confirmed to be the same binary -- never a general cross-binary
    // fallback.
    if same_binary {
        let shared_addresses: Vec<&str> = remaining_a
            .keys()
            .filter(|address| remaining_b.contains_key(*address))
            .copied()
            .collect();

        for address in shared_addresses {
            let function_a = remaining_a
                .remove(address)
                .expect("address was just found in remaining_a");
            let function_b = remaining_b
                .remove(address)
                .expect("address was just found in remaining_b");

            matches.push(make_match(MatchMethod::SameAddress, function_a, function_b));
        }
    }

    let mut unmatched_a: Vec<UnmatchedFunction> = remaining_a
        .into_values()
        .map(|function| UnmatchedFunction {
            entry_address: function.entry_address.clone(),
            name: function.name.clone(),
            namespace: function.namespace.clone(),
            reason: reasons_a
                .remove(function.entry_address.as_str())
                .expect("every remaining function was classified before pass 2"),
        })
        .collect();
    let mut unmatched_b: Vec<UnmatchedFunction> = remaining_b
        .into_values()
        .map(|function| UnmatchedFunction {
            entry_address: function.entry_address.clone(),
            name: function.name.clone(),
            namespace: function.namespace.clone(),
            reason: reasons_b
                .remove(function.entry_address.as_str())
                .expect("every remaining function was classified before pass 2"),
        })
        .collect();

    matches.sort_by(|left, right| {
        left.function_a
            .entry_address
            .cmp(&right.function_a.entry_address)
    });
    unmatched_a.sort_by(|left, right| left.entry_address.cmp(&right.entry_address));
    unmatched_b.sort_by(|left, right| left.entry_address.cmp(&right.entry_address));

    ProjectComparison {
        same_binary,
        matches,
        unmatched_a,
        unmatched_b,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::ghidra_export::{Endianness, FunctionParameter, ProgramMetadata};

    fn function(entry_address: &str, name: &str, namespace: Option<&str>) -> GhidraFunction {
        GhidraFunction {
            entry_address: entry_address.to_owned(),
            name: name.to_owned(),
            return_type: "void".to_owned(),
            parameters: Vec::new(),
            is_external: false,
            is_thunk: false,
            decompiled_code: None,
            calls: Vec::new(),
            strings: Vec::new(),
            library: None,
            thunk_target_address: None,
            namespace: namespace.map(str::to_owned),
        }
    }

    fn export(sha256: &str, functions: Vec<GhidraFunction>) -> GhidraExport {
        GhidraExport {
            schema_version: 2,
            program: ProgramMetadata {
                name: "sample.exe".to_owned(),
                sha256: sha256.to_owned(),
                format: "PE".to_owned(),
                architecture: "x86_64".to_owned(),
                endianness: Endianness::Little,
                image_base: "0x140000000".to_owned(),
                external_entry_points: Vec::new(),
                required_libraries: Vec::new(),
            },
            functions,
            strings: Vec::new(),
            types: Vec::new(),
        }
    }

    const SHA_A: &str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    const SHA_B: &str = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

    #[test]
    fn a_significant_unique_name_present_on_both_sides_matches_by_symbol_name() {
        let a = export(SHA_A, vec![function("0x1000", "authenticate", None)]);
        let b = export(SHA_B, vec![function("0x2000", "authenticate", None)]);

        let comparison = compare_projects(&a, &b);

        assert_eq!(comparison.matches.len(), 1);
        assert_eq!(comparison.matches[0].method, MatchMethod::SymbolName);
        assert!(!comparison.matches[0].same_address);
        assert!(comparison.unmatched_a.is_empty());
        assert!(comparison.unmatched_b.is_empty());
    }

    #[test]
    fn an_auto_generated_name_is_never_matched_even_if_identical_on_both_sides() {
        let a = export(SHA_A, vec![function("0x1000", "FUN_00401000", None)]);
        let b = export(SHA_B, vec![function("0x2000", "FUN_00401000", None)]);

        let comparison = compare_projects(&a, &b);

        assert!(comparison.matches.is_empty());
        assert_eq!(comparison.unmatched_a.len(), 1);
        assert_eq!(
            comparison.unmatched_a[0].reason,
            UnmatchedReason::AutoGeneratedName
        );
        assert_eq!(
            comparison.unmatched_b[0].reason,
            UnmatchedReason::AutoGeneratedName
        );
    }

    #[test]
    fn a_thunk_style_auto_generated_name_is_also_excluded() {
        let a = export(SHA_A, vec![function("0x1000", "thunk_FUN_00401000", None)]);
        let b = export(SHA_B, vec![function("0x2000", "thunk_FUN_00401000", None)]);

        let comparison = compare_projects(&a, &b);

        assert!(comparison.matches.is_empty());
        assert_eq!(
            comparison.unmatched_a[0].reason,
            UnmatchedReason::AutoGeneratedName
        );
    }

    #[test]
    fn a_name_duplicated_within_one_side_is_ambiguous_and_never_matched() {
        // Mirrors real fauxware.elf data: the same import name appears at
        // several PLT/GOT thunk levels, all in the global namespace.
        let a = export(
            SHA_A,
            vec![
                function("0x1000", "puts", None),
                function("0x1100", "puts", None),
            ],
        );
        let b = export(SHA_B, vec![function("0x2000", "puts", None)]);

        let comparison = compare_projects(&a, &b);

        assert!(comparison.matches.is_empty());
        assert_eq!(comparison.unmatched_a.len(), 2);
        assert!(comparison
            .unmatched_a
            .iter()
            .all(|unmatched| unmatched.reason == UnmatchedReason::AmbiguousName));
        // The lone `b` side candidate had no unique counterpart to pair
        // with, so it's `NoCandidate`, not ambiguous itself.
        assert_eq!(
            comparison.unmatched_b[0].reason,
            UnmatchedReason::NoCandidate
        );
    }

    #[test]
    fn namespace_disambiguates_an_otherwise_duplicated_name() {
        let a = export(
            SHA_A,
            vec![
                function("0x1000", "run", Some("Worker")),
                function("0x1100", "run", Some("Scheduler")),
            ],
        );
        let b = export(
            SHA_B,
            vec![
                function("0x2000", "run", Some("Worker")),
                function("0x2100", "run", Some("Scheduler")),
            ],
        );

        let comparison = compare_projects(&a, &b);

        assert_eq!(comparison.matches.len(), 2);
        assert!(comparison.unmatched_a.is_empty());
        assert!(comparison.unmatched_b.is_empty());
    }

    #[test]
    fn a_name_present_only_on_one_side_is_reported_as_no_candidate_not_added_or_removed() {
        let a = export(
            SHA_A,
            vec![
                function("0x1000", "authenticate", None),
                function("0x1100", "legacy_helper", None),
            ],
        );
        let b = export(SHA_B, vec![function("0x2000", "authenticate", None)]);

        let comparison = compare_projects(&a, &b);

        assert_eq!(comparison.matches.len(), 1);
        assert_eq!(comparison.unmatched_a.len(), 1);
        assert_eq!(comparison.unmatched_a[0].name, "legacy_helper");
        assert_eq!(
            comparison.unmatched_a[0].reason,
            UnmatchedReason::NoCandidate
        );
        assert!(comparison.unmatched_b.is_empty());
    }

    #[test]
    fn same_binary_address_pass_recovers_a_pair_that_name_matching_could_not() {
        // Same sha256 (same binary re-analyzed) and a duplicated import
        // name that name-matching must skip as ambiguous -- but since it's
        // confirmed the same binary, matching the exact same address is a
        // legitimate second signal.
        let a = export(
            SHA_A,
            vec![
                function("0x1000", "puts", None),
                function("0x1100", "puts", None),
            ],
        );
        let b = export(
            SHA_A,
            vec![
                function("0x1000", "puts", None),
                function("0x1100", "puts", None),
            ],
        );

        let comparison = compare_projects(&a, &b);

        assert!(comparison.same_binary);
        assert_eq!(comparison.matches.len(), 2);
        assert!(comparison
            .matches
            .iter()
            .all(|function_match| function_match.method == MatchMethod::SameAddress));
        assert!(comparison.unmatched_a.is_empty());
        assert!(comparison.unmatched_b.is_empty());
    }

    #[test]
    fn different_binaries_never_fall_back_to_address_matching() {
        // Same address, same ambiguous name, but a different sha256 --
        // these are two different binaries, so the shared address is
        // coincidental and must never be treated as a match.
        let a = export(
            SHA_A,
            vec![
                function("0x1000", "puts", None),
                function("0x1100", "puts", None),
            ],
        );
        let b = export(
            SHA_B,
            vec![
                function("0x1000", "puts", None),
                function("0x1100", "puts", None),
            ],
        );

        let comparison = compare_projects(&a, &b);

        assert!(!comparison.same_binary);
        assert!(comparison.matches.is_empty());
        assert_eq!(comparison.unmatched_a.len(), 2);
        assert_eq!(comparison.unmatched_b.len(), 2);
    }

    #[test]
    fn a_matched_pair_with_identical_signatures_reports_no_changes() {
        let a = export(SHA_A, vec![function("0x1000", "authenticate", None)]);
        let b = export(SHA_B, vec![function("0x2000", "authenticate", None)]);

        let comparison = compare_projects(&a, &b);

        assert!(comparison.matches[0].changes.is_empty());
    }

    #[test]
    fn a_matched_pair_with_a_changed_signature_and_call_count_reports_both() {
        let mut before = function("0x1000", "authenticate", None);
        before.return_type = "int".to_owned();
        before.parameters = vec![FunctionParameter {
            name: "input".to_owned(),
            data_type: "char *".to_owned(),
        }];

        let mut after = function("0x2000", "authenticate", None);
        after.return_type = "bool".to_owned();
        after.parameters = vec![
            FunctionParameter {
                name: "input".to_owned(),
                data_type: "char *".to_owned(),
            },
            FunctionParameter {
                name: "config".to_owned(),
                data_type: "Config *".to_owned(),
            },
        ];
        after.is_thunk = true;
        after.calls = vec![crate::models::ghidra_export::FunctionCall {
            target_address: Some("0x3000".to_owned()),
            target_name: "strcmp".to_owned(),
        }];

        let a = export(SHA_A, vec![before]);
        let b = export(SHA_B, vec![after]);

        let comparison = compare_projects(&a, &b);
        let changes = &comparison.matches[0].changes;

        assert!(changes
            .iter()
            .any(|change| change.kind == FunctionChangeKind::ReturnType));
        assert!(changes
            .iter()
            .any(|change| change.kind == FunctionChangeKind::Parameters));
        assert!(changes
            .iter()
            .any(|change| change.kind == FunctionChangeKind::ThunkStatus));
        assert!(changes
            .iter()
            .any(|change| change.kind == FunctionChangeKind::OutgoingCallCount));
        assert!(!changes
            .iter()
            .any(|change| change.kind == FunctionChangeKind::ExternalStatus));
    }

    #[test]
    fn a_symbol_name_match_that_also_coincides_in_address_records_same_address() {
        let a = export(SHA_A, vec![function("0x1000", "authenticate", None)]);
        let b = export(SHA_B, vec![function("0x1000", "authenticate", None)]);

        let comparison = compare_projects(&a, &b);

        assert_eq!(comparison.matches[0].method, MatchMethod::SymbolName);
        assert!(comparison.matches[0].same_address);
    }
}
